name: Backend CI Pipeline

on:
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    name: Run Tests and Check Coverage
    runs-on: ubuntu-latest
    env:
      APP_DIR: app/
      TESTS_DIR: app/test/
      PYTHON_VERSION: 3.8
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Detect Changes On Files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            any:
              - '**'
            app:
              - 'app/**'
      
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        if: steps.changes.outputs.app == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        if: steps.changes.outputs.app == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        if: steps.changes.outputs.app == 'true'
        run: |
          python -m pytest -v

      - name: Coverage with Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          base-path: ${{ env.APP_DIR }}
