name: Backend CI Pipeline

on:
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    name: Run Tests and Check Coverage
    runs-on: ubuntu-latest
    env:
      APP_DIR: app/
      TESTS_DIR: app/test/
      PYTHON_VERSION: 3.8
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Detect Changes On Files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            any:
              - '**'
            app:
              - 'app/**'
      
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        if: steps.changes.outputs.app == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        if: steps.changes.outputs.app == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test and Coverage with pytest
        if: steps.changes.outputs.app == 'true'
        run: |
          pytest --cov-report term --cov=$TESTS_DIR

      - name: Coverage Comment
        if: ${{ failure() || steps.changes.outputs.app == 'true' }}
        id: coverage_comment
        uses: ewjoachim/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Store Pull Request Comment to be Posted
        if: ${{ failure() || steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt

      - name: Post Comment
        if: ${{ failure() || steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true' }}
        uses: ewjoachim/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.pull_request.id }}
