name: Backend CI Pipeline

on:
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/backend-ci.yml'

  jobs:
    ci:
      runs-on: ubuntu-latest
      env:
        APP_DIR: app/
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Detect Changes On Files
          id: changes
          uses: dorny/paths-filter@v2
          with:
            filters: |
              any:
                - '**'
              app:
                - 'app/**'
